//! Static HTML report: overview dashboard, risk table, cold/orphan sections.
//! No server; open locally or publish as CI artifact.

use std::collections::HashMap;
use std::io::Write;

use crate::analysis::{TableMetrics, TableRisk, UsageReport};

fn schema_complexity(total_tables: usize, total_fks: usize) -> f64 {
    if total_tables == 0 {
        return 0.0;
    }
    let n = total_tables as f64;
    let f = total_fks as f64;
    ((n * 0.02 + f * 0.05).min(1.0) * 100.0).round() / 100.0
}

fn escape(s: &str) -> String {
    let mut o = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => o.push_str("&amp;"),
            '<' => o.push_str("&lt;"),
            '>' => o.push_str("&gt;"),
            '"' => o.push_str("&quot;"),
            '\'' => o.push_str("&#39;"),
            _ => o.push(c),
        }
    }
    o
}

pub fn render<W: Write>(
    w: &mut W,
    metrics: &[TableMetrics],
    total_tables: usize,
    total_columns: usize,
    total_indexes: usize,
    total_fks: usize,
    usage: Option<&UsageReport>,
) -> std::io::Result<()> {
    let overall_risk = if metrics.is_empty() {
        0.0
    } else {
        metrics.iter().map(|m| m.display_risk()).sum::<f64>() / metrics.len() as f64
    };
    let _critical = metrics.iter().filter(|m| TableRisk::from_score(m.display_risk()) == TableRisk::Critical).count();
    let _high = metrics.iter().filter(|m| TableRisk::from_score(m.display_risk()) == TableRisk::High).count();
    let orphans: Vec<_> = metrics.iter().filter(|m| m.is_orphan).collect();
    let in_cycle: Vec<_> = metrics.iter().filter(|m| m.in_cycle).collect();
    let mut sorted: Vec<&TableMetrics> = metrics.iter().collect();
    sorted.sort_by(|a, b| b.display_risk().partial_cmp(&a.display_risk()).unwrap_or(std::cmp::Ordering::Equal));
    let queries_card = usage
        .map(|u| format!(r#"<div class="card"><strong>{}</strong> Queries analyzed</div>"#, u.total_queries_parsed))
        .unwrap_or_default();
    let complexity = schema_complexity(total_tables, total_fks);
    let hotness_map: HashMap<String, u64> = usage
        .map(|u| u.hot_tables.iter().map(|h| (h.qualified_name.clone(), h.query_count)).collect())
        .unwrap_or_default();

    writeln!(w, r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DBScope Schema Report</title>
  <style>
    :root {{ font-family: system-ui, -apple-system, sans-serif; background: #0d1117; color: #e6edf3; }}
    body {{ max-width: 1200px; margin: 0 auto; padding: 2rem; }}
    h1 {{ font-size: 1.75rem; margin-bottom: 0.5rem; }}
    .overview {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
    .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; }}
    .card strong {{ display: block; font-size: 1.5rem; color: #58a6ff; }}
    .risk-critical {{ color: #f85149; }}
    .risk-high {{ color: #db6d28; }}
    .risk-medium {{ color: #d29922; }}
    .risk-low {{ color: #3fb950; }}
    table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
    th, td {{ text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #30363d; }}
    th {{ background: #161b22; color: #8b949e; font-weight: 600; cursor: pointer; user-select: none; }}
    th:hover {{ background: #21262d; }}
    tr:hover {{ background: #161b22; }}
    section {{ margin: 2rem 0; }}
    section h2 {{ font-size: 1.25rem; margin-bottom: 0.75rem; color: #8b949e; }}
    ul {{ margin: 0; padding-left: 1.5rem; }}
    .meta {{ color: #8b949e; font-size: 0.875rem; margin-top: 2rem; }}
  </style>
</head>
<body>
  <h1>DBScope Schema Report</h1>
  <p class="meta">Static report — no server, no telemetry. Generated by dbscope.</p>

  <section>
    <h2>Overview</h2>
    <div class="overview">
      <div class="card"><strong>{}</strong> Tables</div>
      <div class="card"><strong>{}</strong> Columns</div>
      <div class="card"><strong>{}</strong> Indexes</div>
      <div class="card"><strong>{}</strong> Foreign keys</div>
      <div class="card"><strong>{:.2}</strong> Overall risk score</div>
      <div class="card"><strong>{:.2}</strong> Schema complexity</div>
      {}
    </div>
  </section>

  <section>
    <h2>Dependency graph</h2>
    <p class="meta">FK graph: <code>dbscope-graph.dot</code> — run <code>dot -Tsvg dbscope-graph.dot -o dbscope-graph.svg</code> to view.</p>
  </section>
"#,
        total_tables,
        total_columns,
        total_indexes,
        total_fks,
        overall_risk,
        complexity,
        queries_card,
    )?;
    writeln!(w, r#"
  <section>
    <h2>Risk scoring (explainable)</h2>
    <p class="meta">Table risk = depth (max 0.4) + cycle (0.3 if in cycle) + centrality (max 0.3). Orphans = 0. Impact risk = 0.4×FK_downstream + 0.3×index_deps + 0.3×queries_affected.</p>
  </section>

  <section>
    <h2>Risk table</h2>
    <p>Tables sorted by risk (highest first). Centrality = in/out FK count. FK depth = max path length.</p>
    <table>
      <thead>
        <tr>
          <th>Table</th>
          <th>Centrality (in / out)</th>
          <th>FK depth (out / in)</th>
          <th>Orphan</th>
          <th>In cycle</th>
          <th>Risk</th>"#)?;
    if usage.is_some() {
        writeln!(w, r#"
          <th>Hotness</th>"#)?;
    }
    writeln!(w, r#"
        </tr>
      </thead>
      <tbody>"#)?;

    for m in &sorted {
        let risk = TableRisk::from_score(m.display_risk());
        let risk_class = match risk {
            TableRisk::Critical => "risk-critical",
            TableRisk::High => "risk-high",
            TableRisk::Medium => "risk-medium",
            TableRisk::Low => "risk-low",
        };
        let hotness_cell = if usage.is_some() {
            hotness_map
                .get(&m.qualified_name)
                .map(|c| format!("{}", c))
                .unwrap_or_else(|| "—".to_string())
        } else {
            String::new()
        };
        writeln!(
            w,
            r#"        <tr>
          <td>{}</td>
          <td>{} / {}</td>
          <td>{} / {}</td>
          <td>{}</td>
          <td>{}</td>
          <td class="{}">{}</td>"#,
            escape(&m.qualified_name),
            m.centrality_in,
            m.centrality_out,
            m.fk_depth_out,
            m.fk_depth_in,
            if m.is_orphan { "yes" } else { "no" },
            if m.in_cycle { "yes" } else { "no" },
            risk_class,
            risk.label(),
        )?;
        if usage.is_some() {
            writeln!(w, r#"
          <td>{}</td>"#, escape(&hotness_cell))?;
        }
        writeln!(w, r#"
        </tr>"#)?;
    }

    writeln!(w, r#"      </tbody>
    </table>
  </section>"#)?;

    if !orphans.is_empty() {
        writeln!(w, r#"
  <section>
    <h2>Orphan tables</h2>
    <p>Tables with no foreign key references in or out.</p>
    <ul>"#)?;
        for m in orphans {
            writeln!(w, "      <li>{}</li>", escape(&m.qualified_name))?;
        }
        writeln!(w, "    </ul>\n  </section>")?;
    }

    if !in_cycle.is_empty() {
        writeln!(w, r#"
  <section>
    <h2>Tables in circular dependencies</h2>
    <ul>"#)?;
        for m in in_cycle {
            writeln!(w, "      <li>{}</li>", escape(&m.qualified_name))?;
        }
        writeln!(w, "    </ul>\n  </section>")?;
    }

    if let Some(u) = usage {
        if !u.cold_tables.is_empty() {
            writeln!(w, r#"
  <section>
    <h2>Cold tables (never queried)</h2>
    <ul>"#)?;
            for t in &u.cold_tables {
                writeln!(w, "      <li>{}</li>", escape(&t.0))?;
            }
            writeln!(w, "    </ul>\n  </section>")?;
        }
        if !u.cold_columns.is_empty() {
            writeln!(w, r#"
  <section>
    <h2>Cold columns (never referenced)</h2>
    <ul>"#)?;
            for c in u.cold_columns.iter().take(100) {
                writeln!(w, "      <li>{}.{}</li>", escape(&c.qualified_table), escape(&c.column_name))?;
            }
            writeln!(w, "    </ul>\n  </section>")?;
        }
        if !u.index_suggestions.is_empty() {
            writeln!(w, r#"
  <section>
    <h2>Index suggestions (column in WHERE, no index)</h2>
    <table>
      <thead><tr><th>Table</th><th>Column</th><th>WHERE count</th></tr></thead>
      <tbody>"#)?;
            for s in u.index_suggestions.iter().take(30) {
                writeln!(w, "        <tr><td>{}</td><td>{}</td><td>{}</td></tr>",
                    escape(&s.qualified_table), escape(&s.column_name), s.in_where_count)?;
            }
            writeln!(w, "      </tbody>\n    </table>\n  </section>")?;
        }
    }

    writeln!(w, r#"
  <p class="meta">DBScope — understand your database before you touch it.</p>
</body>
</html>"#)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analysis::TableMetrics;

    fn one_table_metrics() -> Vec<TableMetrics> {
        vec![TableMetrics {
            qualified_name: "public.foo".into(),
            fk_depth_out: 0,
            fk_depth_in: 0,
            is_orphan: true,
            in_cycle: false,
            centrality_out: 0,
            centrality_in: 0,
            risk_score: 0.0,
            risk_breakdown: None,
            operational_weight: None,
            effective_risk: None,
        }]
    }

    #[test]
    fn html_contains_doctype_and_overview() {
        let mut buf = Vec::new();
        render(&mut buf, &one_table_metrics(), 1, 2, 0, 0, None).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("<!DOCTYPE html>"));
        assert!(s.contains("DBScope Schema Report"));
        assert!(s.contains("Overview"));
        assert!(s.contains("public.foo"));
        assert!(s.contains("Risk table"));
    }
}
